# Uses version 2 of the YAML version
version: 2
updates:
  # Enable version updates for Python packages
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates weekly
    schedule:
      interval: "weekly"
    # merge issues occurs a lot with dependabot dependency
    # migration. 
    # To avoid this, we could pull our dependabot PRs locally
    # update our dependency and merge to main branch after that.
    #
    # The target branch rule, allows us to checkout locally to
    # a dependency branch.
    target-branch: "dependencies"
