# This workflow keeps our 'dependencies' branch
# up to date with our main branch.
#
# source: https://www.hacksoft.io/blog/managing-dependencies-with-github-dependabot-and-actions#dependabot

name: Auto Rebase

on:
 push:
  branches:
   - master

jobs:
  rebase:
   name: Rebase `dependencies` into `master`
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
      with:
        # without fetch-depth one would be unable to push
        # refs to dest repo
        fetch-depth: 0
        ref: dependencies
    - run: > 
        # Git Idenfication configuration
        git config user.email github-actions@github.com
        git config user.name github-actions
        git rebase orgin/master
        # to prevent unexpected outcome we using
        # --force-with-lease instead of --force
        # this ensures rebase of branch.
        git push origin dependencies --force-with-lease
